<?php

namespace Database\Seeders\Inventori;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Inventori\I_Obat;

// call external package
use Faker\Factory as Faker;
use Illuminate\Support\Str;

class I_ObatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create('id_ID');
        $data_obat = array(
            array('id' => '1','nama_obat' => 'Acyclovir 400 mg tab','kode_obat' => 'AC2','kandungan' => ' Acyclovir '),
            array('id' => '3','nama_obat' => 'Acyclovir cream','kode_obat' => 'AC3','kandungan' => ' Acyclovir '),
            array('id' => '4','nama_obat' => 'Akita tab','kode_obat' => '','kandungan' => ' attapulgite '),
            array('id' => '5','nama_obat' => 'Alinamin F tab','kode_obat' => 'AL1','kandungan' => ''),
            array('id' => '6','nama_obat' => 'Allopurinol 100 mg tab','kode_obat' => 'AL3','kandungan' => ' Allupurinol '),
            array('id' => '7','nama_obat' => 'Alerzin syr','kode_obat' => '','kandungan' => ' cetirizine '),
            array('id' => '8','nama_obat' => 'Aillin TM','kode_obat' => 'AL4','kandungan' => ''),
            array('id' => '9','nama_obat' => 'Ambroxol  ','kode_obat' => 'AM2','kandungan' => ' Ambroxol '),
            array('id' => '10','nama_obat' => 'Ambroxol syrup','kode_obat' => 'AM3','kandungan' => ' Ambroxol '),
            array('id' => '11','nama_obat' => 'Amlodipin 10 mg tab','kode_obat' => 'AM4','kandungan' => ' Amlodipin '),
            array('id' => '12','nama_obat' => 'Amlodipin 10 mg tab new','kode_obat' => '','kandungan' => ''),
            array('id' => '13','nama_obat' => 'Amlodipin 5 mg tab','kode_obat' => 'AM5','kandungan' => ' Amlodipin '),
            array('id' => '14','nama_obat' => 'Amoxicillin Syrup','kode_obat' => '','kandungan' => ' Amoxicilin '),
            array('id' => '15','nama_obat' => 'amlodipin 5 mg tab new','kode_obat' => '','kandungan' => ''),
            array('id' => '16','nama_obat' => 'Amoxicilin tab 500 mg','kode_obat' => '','kandungan' => ''),
            array('id' => '17','nama_obat' => 'Amoxicillin Syrup','kode_obat' => 'AM7','kandungan' => ''),
            array('id' => '18','nama_obat' => 'Anastan','kode_obat' => 'AN1','kandungan' => ' asmef '),
            array('id' => '19','nama_obat' => 'Antasida Syr','kode_obat' => 'AN2','kandungan' => ''),
            array('id' => '20','nama_obat' => 'Antasida DOEN','kode_obat' => 'AN3','kandungan' => ''),
            array('id' => '21','nama_obat' => 'asam mefenamat new','kode_obat' => '','kandungan' => ''),
            array('id' => '22','nama_obat' => 'Antrain inj','kode_obat' => 'AN6','kandungan' => ' Metamizol Na '),
            array('id' => '23','nama_obat' => 'Asering','kode_obat' => 'AS4','kandungan' => ' CaCL,NaCL,Na asetat '),
            array('id' => '24','nama_obat' => 'anvomer','kode_obat' => '','kandungan' => ' pyridoxin HCL, pyrathiazine-8-chlorotheopylnate '),
            array('id' => '25','nama_obat' => 'aspilet','kode_obat' => '10','kandungan' => ''),
            array('id' => '26','nama_obat' => 'aquabides/ WFI','kode_obat' => 'AQ1','kandungan' => ''),
            array('id' => '27','nama_obat' => 'Bufacomb','kode_obat' => 'BU1','kandungan' => ''),
            array('id' => '28','nama_obat' => 'Bedak salicyl botol','kode_obat' => 'BE1','kandungan' => ' Asam Salisilat '),
            array('id' => '29','nama_obat' => 'betahistin','kode_obat' => 'BE2','kandungan' => ' Betahistin '),
            array('id' => '30','nama_obat' => 'Betason N','kode_obat' => 'BE3','kandungan' => ' betametason '),
            array('id' => '31','nama_obat' => 'Betametason cream','kode_obat' => 'BE4','kandungan' => ''),
            array('id' => '32','nama_obat' => 'Biothicol syr','kode_obat' => '','kandungan' => ''),
            array('id' => '33','nama_obat' => 'Bufect Forte syr','kode_obat' => 'BU2','kandungan' => ' ibuprofen '),
            array('id' => '34','nama_obat' => 'Bufect syr','kode_obat' => 'BU4','kandungan' => ' ibuprofen '),
            array('id' => '35','nama_obat' => 'bisoprolol','kode_obat' => '','kandungan' => ''),
            array('id' => '36','nama_obat' => 'bioplacenton','kode_obat' => 'BI3','kandungan' => ''),
            array('id' => '37','nama_obat' => 'burnazin plus','kode_obat' => '','kandungan' => ''),
            array('id' => '38','nama_obat' => 'Burnazin 33 g Zalf','kode_obat' => 'BU5','kandungan' => ' Silver Sulfadiazin '),
            array('id' => '39','nama_obat' => 'Caloma ','kode_obat' => 'CA1','kandungan' => ' multivitamin dan mineral '),
            array('id' => '40','nama_obat' => 'Caladin lotion kecil','kode_obat' => 'CA2','kandungan' => ''),
            array('id' => '41','nama_obat' => 'Captopril 12.5 mg','kode_obat' => 'm','kandungan' => ' Captopril 12,5 mg '),
            array('id' => '42','nama_obat' => 'Captopril 25 mg','kode_obat' => 'CA4','kandungan' => ' captopril 25 mg '),
            array('id' => '43','nama_obat' => 'Carbidu','kode_obat' => 'CA5','kandungan' => ' dexamethason 0.5mg '),
            array('id' => '44','nama_obat' => 'Cataflam 50mg','kode_obat' => 'CA6','kandungan' => ' kalium diklofenak '),
            array('id' => '45','nama_obat' => 'caviplex CDEZ','kode_obat' => 'CA9','kandungan' => ''),
            array('id' => '46','nama_obat' => 'Caviplex syr','kode_obat' => 'CA10','kandungan' => ''),
            array('id' => '47','nama_obat' => 'Cefco','kode_obat' => 'CE1','kandungan' => ' cefadroxil 500 '),
            array('id' => '48','nama_obat' => 'cefadroxil caps','kode_obat' => 'CE2','kandungan' => ''),
            array('id' => '49','nama_obat' => 'cefadroxil syr','kode_obat' => '','kandungan' => ''),
            array('id' => '50','nama_obat' => 'cefadroxil syr new','kode_obat' => '','kandungan' => ''),
            array('id' => '51','nama_obat' => 'cefixim tab','kode_obat' => 'CE4','kandungan' => ' Cefixime '),
            array('id' => '52','nama_obat' => 'Cefixim syrup','kode_obat' => 'CE5','kandungan' => ' Cefixime '),
            array('id' => '53','nama_obat' => 'Cefotaxime 1 G inj','kode_obat' => 'CE6','kandungan' => ' Cefotaxime '),
            array('id' => '54','nama_obat' => 'Ceftriaxon 1 G inj','kode_obat' => 'CE7','kandungan' => ' Ceftriaxon '),
            array('id' => '55','nama_obat' => 'Cetirizine','kode_obat' => 'CE9','kandungan' => ''),
            array('id' => '56','nama_obat' => 'Ciprofloxacin tab','kode_obat' => 'CI1','kandungan' => ' Ciprofloxacin 500 mg '),
            array('id' => '57','nama_obat' => 'Clindamycin 150 mg','kode_obat' => 'CL1','kandungan' => ' Clindamycin 150 mg '),
            array('id' => '58','nama_obat' => 'Clindamycin 300 mg tab','kode_obat' => 'CL2','kandungan' => ' Clindamycin 300 mg '),
            array('id' => '59','nama_obat' => 'corovit','kode_obat' => '','kandungan' => ''),
            array('id' => '60','nama_obat' => 'Cortidex Inj','kode_obat' => 'e','kandungan' => ''),
            array('id' => '61','nama_obat' => 'Combantrin syrup','kode_obat' => 'CO6','kandungan' => ''),
            array('id' => '62','nama_obat' => 'Cotrimoxazole tab','kode_obat' => 'CO8','kandungan' => ' Trimetoprim sulfametoksazol '),
            array('id' => '63','nama_obat' => 'Combivent nebul','kode_obat' => 'CO9','kandungan' => ''),
            array('id' => '64','nama_obat' => 'CTM 4 mg  kalengan','kode_obat' => 'CT1','kandungan' => ' s '),
            array('id' => '65','nama_obat' => 'Curcuma 200 mg tab','kode_obat' => 'CU1','kandungan' => ' Ext curcuma xanthoriza '),
            array('id' => '66','nama_obat' => 'Cyclogeston','kode_obat' => 'CY1','kandungan' => ''),
            array('id' => '67','nama_obat' => 'Demacolin','kode_obat' => '','kandungan' => ''),
            array('id' => '68','nama_obat' => 'Deponeo inj','kode_obat' => 'DE1','kandungan' => ' Medroxyprogeston acetat '),
            array('id' => '69','nama_obat' => 'Dexamethason tab','kode_obat' => 'DE2','kandungan' => ' Dexamethason '),
            array('id' => '70','nama_obat' => 'Dexamethason inj','kode_obat' => 'DE3','kandungan' => ' Dexametason 0,5 mg '),
            array('id' => '71','nama_obat' => 'dexteem plus','kode_obat' => 'DE4','kandungan' => ' Deksametason 0,5 mg dan '),
            array('id' => '72','nama_obat' => 'dexycol new','kode_obat' => '','kandungan' => ''),
            array('id' => '73','nama_obat' => 'Dextrose 5% ','kode_obat' => 'DE10','kandungan' => ' Dextrose  5 % '),
            array('id' => '74','nama_obat' => 'Digoxin tab','kode_obat' => 'DI2','kandungan' => ' Digoxin 0,25 mg '),
            array('id' => '75','nama_obat' => 'Disflatyl','kode_obat' => 'DI3','kandungan' => ''),
            array('id' => '76','nama_obat' => 'Dimenhydrinate','kode_obat' => 'DI4','kandungan' => ' dimenhydrinate '),
            array('id' => '77','nama_obat' => 'Dolo-licobion','kode_obat' => 'DO1','kandungan' => ' metampiron, vit b1, vitb6,vit12 '),
            array('id' => '78','nama_obat' => 'Domperidone syr','kode_obat' => '','kandungan' => ' domperidon '),
            array('id' => '79','nama_obat' => 'Doxyciclin 100 mg tab new','kode_obat' => '','kandungan' => ''),
            array('id' => '80','nama_obat' => 'Dumin rectal','kode_obat' => 'DU2','kandungan' => '  doxy  '),
            array('id' => '81','nama_obat' => 'Dulcolax10 mg supp','kode_obat' => 'DU3','kandungan' => ' Bisacodyl 10 mg '),
            array('id' => '82','nama_obat' => 'Dulcolax tablet','kode_obat' => 'DU4','kandungan' => ' Bisacodyl '),
            array('id' => '83','nama_obat' => 'Ephineprin inj','kode_obat' => 'EP4','kandungan' => ''),
            array('id' => '84','nama_obat' => 'Erlamicetin salep mata','kode_obat' => 'ER3','kandungan' => ' Chloramphenicol '),
            array('id' => '85','nama_obat' => 'Erlamicetin tetes telinga','kode_obat' => 'ER4','kandungan' => ' Chloramphenicol '),
            array('id' => '86','nama_obat' => 'Erlamicetin PLUS TM','kode_obat' => 'ER6','kandungan' => ' Chloramphenicol '),
            array('id' => '87','nama_obat' => 'Erlaflu Syr','kode_obat' => '','kandungan' => ''),
            array('id' => '88','nama_obat' => 'Eryra 500 mg tab','kode_obat' => 'ER8','kandungan' => ' Erytromycin '),
            array('id' => '89','nama_obat' => 'Eryra 500 mg tab new','kode_obat' => '','kandungan' => ''),
            array('id' => '90','nama_obat' => 'Etabion','kode_obat' => 'ET1','kandungan' => ' FE '),
            array('id' => '91','nama_obat' => 'Farsifen 400 mg tab new','kode_obat' => '','kandungan' => ''),
            array('id' => '92','nama_obat' => 'FG Troches tab new','kode_obat' => '','kandungan' => ''),
            array('id' => '93','nama_obat' => 'flagystatin ovula','kode_obat' => 'FL1','kandungan' => ''),
            array('id' => '94','nama_obat' => 'Flucadex syr','kode_obat' => 'FL2','kandungan' => ' pct, gg, dmp, propyl,ctm '),
            array('id' => '95','nama_obat' => 'flutop c','kode_obat' => 'FL3','kandungan' => ''),
            array('id' => '96','nama_obat' => 'folarin 400','kode_obat' => 'FO1','kandungan' => ' asam folat '),
            array('id' => '97','nama_obat' => 'folarin 1000','kode_obat' => 'FO2','kandungan' => ' asam folat '),
            array('id' => '98','nama_obat' => 'Furosemid 40 mg tab','kode_obat' => 'FU1','kandungan' => ' Furosemid 40 mg '),
            array('id' => '99','nama_obat' => 'Forumen ear drop','kode_obat' => 'FO3','kandungan' => ' docusate sodium '),
            array('id' => '100','nama_obat' => 'Gentian violet','kode_obat' => 'GE2','kandungan' => ''),
            array('id' => '101','nama_obat' => 'gemfibrozil','kode_obat' => 'GE5','kandungan' => ' gemfibrozil '),
            array('id' => '102','nama_obat' => 'GG tab','kode_obat' => 'GG1','kandungan' => ' Gliseryl guaicolat '),
            array('id' => '103','nama_obat' => 'Glibenclamid 5 mg tab','kode_obat' => 'GL1','kandungan' => ' \\ '),
            array('id' => '104','nama_obat' => 'glimepirid tab 2 mg','kode_obat' => '','kandungan' => ''),
            array('id' => '105','nama_obat' => 'Glimepirid tab 3 mg','kode_obat' => '','kandungan' => ''),
            array('id' => '106','nama_obat' => 'Grantusif','kode_obat' => 'GR2','kandungan' => ''),
            array('id' => '107','nama_obat' => 'gentamicyn SK','kode_obat' => '','kandungan' => ' gentamicin '),
            array('id' => '108','nama_obat' => 'Genoint cream','kode_obat' => 'GE5','kandungan' => ' gentamicin '),
            array('id' => '109','nama_obat' => 'genoint salep mata','kode_obat' => 'GE6','kandungan' => ' gentamicin '),
            array('id' => '110','nama_obat' => 'Genoint Tetes Mata','kode_obat' => '','kandungan' => ''),
            array('id' => '111','nama_obat' => 'guanistrep syr','kode_obat' => 'GU2','kandungan' => ''),
            array('id' => '112','nama_obat' => 'hidrocortison 1%','kode_obat' => 'HI1','kandungan' => ' Hidrocortisone          '),
            array('id' => '113','nama_obat' => 'hufadon syr','kode_obat' => 'HU1','kandungan' => ' domperidon '),
            array('id' => '114','nama_obat' => 'hufanoxil','kode_obat' => '','kandungan' => ''),
            array('id' => '115','nama_obat' => 'hufabion','kode_obat' => 'HU3','kandungan' => ' fe '),
            array('id' => '116','nama_obat' => 'Hufarizine syr','kode_obat' => '','kandungan' => ' cetirizine syr '),
            array('id' => '117','nama_obat' => 'Hemobion','kode_obat' => 'HE2','kandungan' => ' Fe '),
            array('id' => '118','nama_obat' => 'hydrocortison 2,5%','kode_obat' => 'HY1','kandungan' => ' Hidrocortisone          '),
            array('id' => '119','nama_obat' => 'Itamol','kode_obat' => '','kandungan' => ' paracetamol '),
            array('id' => '120','nama_obat' => 'ISDN 5 mg tab','kode_obat' => 'IS1','kandungan' => ' Isisorbid dinitrat 5 mg '),
            array('id' => '121','nama_obat' => 'kaltrofen supp','kode_obat' => 'KA2','kandungan' => ''),
            array('id' => '122','nama_obat' => 'Kalk (novakalk)','kode_obat' => 'KA4','kandungan' => ''),
            array('id' => '123','nama_obat' => 'Kalnex 500 mg tab','kode_obat' => 'KA11','kandungan' => ' Asam tranexsamat '),
            array('id' => '124','nama_obat' => 'Ketoconazole 10 gr','kode_obat' => 'KE1','kandungan' => ' Ketoconazol '),
            array('id' => '125','nama_obat' => 'Ketoconazole tab','kode_obat' => 'KE2','kandungan' => ' Ketoconazol '),
            array('id' => '126','nama_obat' => 'Ketorolac 30 mg inj','kode_obat' => 'KE3','kandungan' => ' Ketorolac  '),
            array('id' => '127','nama_obat' => 'Lactamam','kode_obat' => 'LA1','kandungan' => ''),
            array('id' => '128','nama_obat' => 'Lagesil 100 mL','kode_obat' => 'LA3','kandungan' => ''),
            array('id' => '129','nama_obat' => 'Lansoprazol','kode_obat' => 'LA4','kandungan' => ' Lanzoprazolee '),
            array('id' => '130','nama_obat' => 'lapimuc tab','kode_obat' => '','kandungan' => ''),
            array('id' => '131','nama_obat' => 'lacto b new','kode_obat' => '','kandungan' => ''),
            array('id' => '132','nama_obat' => 'Lecozinc Syr','kode_obat' => '','kandungan' => ''),
            array('id' => '133','nama_obat' => 'lecozinc tab','kode_obat' => '','kandungan' => ''),
            array('id' => '134','nama_obat' => 'Licopec','kode_obat' => 'LI4','kandungan' => ' attapulgit '),
            array('id' => '135','nama_obat' => 'Lidocain inj','kode_obat' => 'LI6','kandungan' => ' lidocain hcl '),
            array('id' => '136','nama_obat' => 'Lodecon tab','kode_obat' => '','kandungan' => ''),
            array('id' => '137','nama_obat' => 'Lodecon Tab','kode_obat' => '','kandungan' => ''),
            array('id' => '138','nama_obat' => ' Loratadin','kode_obat' => 'LO3','kandungan' => ''),
            array('id' => '139','nama_obat' => 'Lostacef','kode_obat' => 'LO4','kandungan' => ' cefadroxil 500 '),
            array('id' => '140','nama_obat' => 'metamidone inj','kode_obat' => '','kandungan' => ''),
            array('id' => '141','nama_obat' => 'Metformin 500 mg tab','kode_obat' => 'ME3','kandungan' => ' Metformin '),
            array('id' => '142','nama_obat' => 'metylprednisolon 4 mg tab','kode_obat' => 'ME4','kandungan' => ' metylprednisolon '),
            array('id' => '143','nama_obat' => 'Metronidazole 500 mg tab','kode_obat' => 'ME5','kandungan' => ' metronidazol '),
            array('id' => '144','nama_obat' => 'Metvell tab','kode_obat' => 'ME6','kandungan' => ' Methyl ergometrin '),
            array('id' => '145','nama_obat' => 'Metvell inj','kode_obat' => 'ME7','kandungan' => ' Methyl ergometrin '),
            array('id' => '146','nama_obat' => 'MgSO4 inj 20*/ 25 ml','kode_obat' => 'MG1','kandungan' => ' Magnesium sulfate '),
            array('id' => '147','nama_obat' => 'MgSO4 inj 40* /25 ml','kode_obat' => 'MG2','kandungan' => ' Magnesium sulfate '),
            array('id' => '148','nama_obat' => 'Microgest','kode_obat' => 'MIC1','kandungan' => ''),
            array('id' => '149','nama_obat' => 'Microlac rektal','kode_obat' => 'MI1','kandungan' => ' Na Lauril Sulfoasetat,Na  '),
            array('id' => '150','nama_obat' => 'Myconazol cream','kode_obat' => 'MY1','kandungan' => ' miconazol  '),
            array('id' => '151','nama_obat' => 'Natrium diklofenak tab','kode_obat' => '','kandungan' => ''),
            array('id' => '152','nama_obat' => 'New Diatab','kode_obat' => '','kandungan' => ''),
            array('id' => '153','nama_obat' => 'Neurobion 5000 inj','kode_obat' => 'NE1','kandungan' => ' vit. B1, b6, b12  '),
            array('id' => '154','nama_obat' => 'Neurodex','kode_obat' => 'NE3','kandungan' => ' Vit B1,Vit B6,Vit B12 '),
            array('id' => '155','nama_obat' => 'neurotropic inj','kode_obat' => '','kandungan' => ''),
            array('id' => '156','nama_obat' => 'Nifedipin 10 mg tab','kode_obat' => 'NI1','kandungan' => ' Nifedipine 10 mg '),
            array('id' => '157','nama_obat' => 'novaxifen syr','kode_obat' => '','kandungan' => ' ibuprofen '),
            array('id' => '158','nama_obat' => 'Novagesic tab','kode_obat' => '','kandungan' => ' Parasetamol '),
            array('id' => '159','nama_obat' => 'Novamox syr','kode_obat' => '','kandungan' => ' Amoxicilin '),
            array('id' => '160','nama_obat' => 'Norit tab','kode_obat' => 'NO1','kandungan' => ' carbon '),
            array('id' => '161','nama_obat' => 'NS otsu','kode_obat' => 'NS1','kandungan' => ' ` '),
            array('id' => '162','nama_obat' => 'NS 25 ml','kode_obat' => 'NS3','kandungan' => ' Nacl '),
            array('id' => '163','nama_obat' => 'OBH Syrup intrasal','kode_obat' => 'OB2','kandungan' => ''),
            array('id' => '164','nama_obat' => 'Omeprazole injeksi','kode_obat' => 'OM1','kandungan' => ' omeprazol 40 mg '),
            array('id' => '165','nama_obat' => 'Omeprazole 20mg  tab','kode_obat' => 'OM2','kandungan' => ' omeprazole 20 mg '),
            array('id' => '166','nama_obat' => 'Ondancentron 4mg inj new','kode_obat' => '','kandungan' => ''),
            array('id' => '167','nama_obat' => 'Ondancetron 4 mg','kode_obat' => 'ON3','kandungan' => ''),
            array('id' => '168','nama_obat' => 'Oralit','kode_obat' => 'OR1','kandungan' => ''),
            array('id' => '169','nama_obat' => 'Orezinc syr','kode_obat' => 'OR2','kandungan' => ' Zinc Sulfat '),
            array('id' => '170','nama_obat' => 'Osteocal','kode_obat' => 'OS1','kandungan' => ' kalsium '),
            array('id' => '171','nama_obat' => 'Oxytocin inj','kode_obat' => 'OX1','kandungan' => ''),
            array('id' => '172','nama_obat' => 'Oxyla inj','kode_obat' => 'OX2','kandungan' => ' oxytocin '),
            array('id' => '173','nama_obat' => 'Phyfion inj','kode_obat' => 'PH2','kandungan' => ''),
            array('id' => '174','nama_obat' => 'Phytomenadione inj','kode_obat' => 'PH3','kandungan' => ' vit k '),
            array('id' => '175','nama_obat' => 'paracetamol syr stroberi','kode_obat' => 'PA2','kandungan' => ' paracetamol '),
            array('id' => '176','nama_obat' => 'Parasetamol Tab','kode_obat' => 'PA3','kandungan' => ' Parasetamol '),
            array('id' => '177','nama_obat' => 'paraco syr','kode_obat' => 'PA4','kandungan' => ' paracetamol '),
            array('id' => '178','nama_obat' => 'paraco drop ','kode_obat' => 'PA6','kandungan' => ' paracetamol '),
            array('id' => '179','nama_obat' => 'Pehacain inj','kode_obat' => 'PE1','kandungan' => ' lidokain inj, epineprin '),
            array('id' => '180','nama_obat' => 'pirofel','kode_obat' => 'PI3','kandungan' => ' Piroxicam '),
            array('id' => '181','nama_obat' => 'Piroxicam 10 mg tab','kode_obat' => 'PI4','kandungan' => ' Piroxicam '),
            array('id' => '182','nama_obat' => 'Piroxicam 20 mg tab','kode_obat' => 'PI5','kandungan' => ' Piroxicam '),
            array('id' => '183','nama_obat' => 'proterin','kode_obat' => 'PR1','kandungan' => ' isoxuprine '),
            array('id' => '184','nama_obat' => 'primolut N','kode_obat' => 'PR2','kandungan' => ''),
            array('id' => '185','nama_obat' => 'Primperan Inj','kode_obat' => 'PR4','kandungan' => ' Metoclopramid '),
            array('id' => '186','nama_obat' => 'PRORIS SUPP','kode_obat' => 'PR5','kandungan' => ' Ibuprofen supp '),
            array('id' => '187','nama_obat' => 'Prolacta Mother tab','kode_obat' => 'PR6','kandungan' => ' DHA,EPA '),
            array('id' => '188','nama_obat' => 'Propanolol 10 mg tab','kode_obat' => 'PR7','kandungan' => ''),
            array('id' => '189','nama_obat' => 'Ranitadin inj','kode_obat' => 'RA1','kandungan' => ''),
            array('id' => '190','nama_obat' => 'Ranitidin tab','kode_obat' => 'RA2','kandungan' => ' Ranitidin '),
            array('id' => '191','nama_obat' => 'Rohto','kode_obat' => '','kandungan' => ''),
            array('id' => '192','nama_obat' => 'Recodryl','kode_obat' => 'RE1','kandungan' => ' dipenhidramine '),
            array('id' => '193','nama_obat' => 'Regumen','kode_obat' => '','kandungan' => ' norethisterone '),
            array('id' => '194','nama_obat' => 'Rl otsu','kode_obat' => 'RL1','kandungan' => ''),
            array('id' => '195','nama_obat' => 'Salbutamol 2 mg tab','kode_obat' => 'SA2','kandungan' => ' salbutamol '),
            array('id' => '196','nama_obat' => 'salep24','kode_obat' => 'SA4','kandungan' => ''),
            array('id' => '197','nama_obat' => 'Sanmol tab','kode_obat' => 'SA5','kandungan' => ' Paracetamol '),
            array('id' => '198','nama_obat' => 'sanmol syr','kode_obat' => 'SA6','kandungan' => ' paracetamol '),
            array('id' => '199','nama_obat' => 'Sanprima syrup','kode_obat' => 'SA7','kandungan' => ' Trimetoprim sulfametoksazol '),
            array('id' => '200','nama_obat' => 'scabimite 10 grcream','kode_obat' => 'SC1','kandungan' => ' gammexane, usnic acid '),
            array('id' => '201','nama_obat' => 'Selediar Tab','kode_obat' => '','kandungan' => ''),
            array('id' => '202','nama_obat' => 'Sucralfat Syr','kode_obat' => '','kandungan' => ''),
            array('id' => '203','nama_obat' => 'sucralfat syr new','kode_obat' => '','kandungan' => ''),
            array('id' => '204','nama_obat' => 'Suprabion','kode_obat' => 'SU1','kandungan' => ' fe, vit c,as.folat '),
            array('id' => '205','nama_obat' => 'Superhoid rectal supp','kode_obat' => 'SU2','kandungan' => ' Hycocyne butil bromide,Metampiron '),
            array('id' => '206','nama_obat' => 'sirplus syr','kode_obat' => 'SI1','kandungan' => ''),
            array('id' => '207','nama_obat' => 'Silex','kode_obat' => 'SI2','kandungan' => ''),
            array('id' => '208','nama_obat' => 'Simvastatin 10 mg tab','kode_obat' => 'SI3','kandungan' => ' simvastatin '),
            array('id' => '209','nama_obat' => 'spasminal','kode_obat' => 'SP1','kandungan' => '   '),
            array('id' => '210','nama_obat' => 'Stesolid supp','kode_obat' => '','kandungan' => ' diazepam '),
            array('id' => '211','nama_obat' => 'Synbio kap','kode_obat' => 'SY1','kandungan' => ' Lactobasilus Acidophilus, Bifidobacterium longum, FOS '),
            array('id' => '212','nama_obat' => 'Thiampenicol','kode_obat' => 'THI','kandungan' => ' Thiampenicol '),
            array('id' => '213','nama_obat' => 'Thrombophob Gel 20 G','kode_obat' => 'TH2','kandungan' => ' Heparin,Nicotinic acid benzylester '),
            array('id' => '214','nama_obat' => 'Triocid','kode_obat' => 'TR5','kandungan' => ' Al(OH)2, Mg(OH)2 '),
            array('id' => '215','nama_obat' => 'Urotractin 400 tab','kode_obat' => 'UR1','kandungan' => ' pipemidic acid '),
            array('id' => '216','nama_obat' => '  Utrogestan','kode_obat' => 'UT1','kandungan' => ' micronised progesterone '),
            array('id' => '217','nama_obat' => 'Valisanbe injeksi','kode_obat' => '','kandungan' => ''),
            array('id' => '218','nama_obat' => 'Valenor','kode_obat' => '','kandungan' => ''),
            array('id' => '219','nama_obat' => 'Ventolin nebul','kode_obat' => '','kandungan' => ''),
            array('id' => '220','nama_obat' => 'vesperum tab','kode_obat' => 'VE4','kandungan' => ' Domperidon '),
            array('id' => '221','nama_obat' => 'vosea syr','kode_obat' => 'VO1','kandungan' => ' Metoclopramid '),
            array('id' => '222','nama_obat' => 'vosea','kode_obat' => 'VO1','kandungan' => ' Metoclopramid '),
            array('id' => '223','nama_obat' => 'vosea new','kode_obat' => '','kandungan' => ''),
            array('id' => '224','nama_obat' => 'Vitamin B1 100 mg','kode_obat' => 'VI1','kandungan' => '   '),
            array('id' => '225','nama_obat' => 'Vitamin B6 tab','kode_obat' => 'VI2','kandungan' => ' Vit B6 '),
            array('id' => '226','nama_obat' => 'Vitamin B Complex','kode_obat' => 'VI3','kandungan' => ' o '),
            array('id' => '227','nama_obat' => 'Vitamin C 100 mg','kode_obat' => 'VI4','kandungan' => ' Vit c '),
            array('id' => '228','nama_obat' => 'Vitacimin ','kode_obat' => 'VI6','kandungan' => ' vit C 500 mg '),
            array('id' => '229','nama_obat' => 'Voltadex','kode_obat' => 'VO1','kandungan' => ' natrium diklofenak '),
            array('id' => '230','nama_obat' => 'Yusimox syr','kode_obat' => 'YU1','kandungan' => ''),
            array('id' => '231','nama_obat' => 'Zinc Tab','kode_obat' => 'ZI1','kandungan' => ' seng sulfat monohidrat '),
            array('id' => '232','nama_obat' => 'zinc syr','kode_obat' => 'ZI2','kandungan' => ''),
            array('id' => '233','nama_obat' => 'ZincKid Syr','kode_obat' => 'ZI3','kandungan' => ''),
            array('id' => '234','nama_obat' => 'Zipha tab','kode_obat' => 'ZI3','kandungan' => ' Zinc Sulfat ')
        );

        foreach ($data_obat as $key => $value) {
            $obat = new I_Obat();
            $obat->uuid = Str::uuid();
            $obat->nama_obat = $value['nama_obat'];
            $obat->kode_obat = $value['kode_obat'];
            $obat->kandungan = $value['kandungan'];
            $obat->jumlah_obat = $faker->numberBetween($min = 1, $max = 100);
            $obat->harga_obat = $faker->numberBetween($min = 1000, $max = 100000);
            $obat->save();
        };
    }
}
